// Copyright (c) 2026 MeedyaSuite
// Licensed under the MIT License. See LICENSE file in the project root.
//
// Music stems metadata.
//
// Stems (drums-only, vocals-only, instrumental, etc.) are generated by
// Demucs, Spleeter, Moises, LANDR Stems, Audioshake, and shipped natively
// by DJ tools (NI Stems, Beatport Stems, VirtualDJ, DJ.Studio).
// This module defines a `MeedyaMeta:Stem*` schema so MeedyaSuite tools
// can group, present, and convert stems while preserving the linkage to
// the original full-mix recording.
//
// **No standards-first override applies** — there is no widely-supported
// stem-metadata standard across ID3v2 / Vorbis / MP4. All stem tags live
// in the `MeedyaMeta:*` namespace.

use std::fmt;
use std::str::FromStr;

use lofty::tag::Tag;
use serde::{Deserialize, Serialize};

use crate::meedya_atom::{clear_meedya_atom, read_meedya_atom, write_meedya_atom};

// Atom names
const ATOM_ROLE: &str = "StemRole";
const ATOM_INSTRUMENTS: &str = "StemInstruments";
const ATOM_COLLECTION_ID: &str = "StemCollectionId";
const ATOM_PARENT_TRACK_ID: &str = "StemParentTrackId";
const ATOM_SOURCE: &str = "StemSource";
const ATOM_TOTAL_COUNT: &str = "StemTotalCount";
const ATOM_INDEX: &str = "StemIndex";
const ATOM_MODEL_VERSION: &str = "StemModelVersion";

// ============================================================
// Public Types
// ============================================================

/// Full stem metadata recovered from a file.
///
/// `role` is the only required field at write time (a stem with no role
/// isn't really a stem). All others are optional.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StemMetadata {
    /// What musical component this stem represents.
    pub role: StemRole,
    /// Optional finer detail: `["kick", "snare", "hat"]` for a drums stem,
    /// `["lead-synth"]` for a melody stem. Recommended vocabularies are in
    /// the module docs but the field accepts any string for forward-compat.
    pub instruments: Vec<String>,
    /// Groups stems of the same original track together. UUID by convention.
    pub collection_id: Option<String>,
    /// Reference to the original full-mix recording — MusicBrainz recording
    /// ID, AcoustID UUID, ISRC, or a caller-defined identifier.
    pub parent_track_id: Option<String>,
    /// What tool produced this stem.
    pub source: StemSource,
    /// How many stems make up the full collection (4 for a typical 4-stem
    /// split).
    pub total_count: Option<u8>,
    /// This stem's 1-based position in the collection.
    pub index: Option<u8>,
    /// If AI-generated, what model + version (e.g. "demucs-v4.0.0-htdemucs").
    pub model_version: Option<String>,
}

/// What musical component a stem represents.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum StemRole {
    Drums,
    Bass,
    Vocals,
    Melody,
    Harmony,
    /// Effects, percussion sweeps, risers, atmospherics, etc.
    Fx,
    /// Catch-all for stem roles not covered above (e.g., "piano-only",
    /// "guitar", "lead-vocals", "backing-vocals" if you want to be finer
    /// than the canonical set).
    Other(String),
    /// The full mixed-down track. Present in some stems collections that
    /// include the original alongside the splits.
    FullMix,
}

/// What tool produced a stem.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum StemSource {
    /// facebookresearch/demucs (open-source).
    Demucs,
    /// deezer/spleeter (open-source).
    Spleeter,
    /// moises.ai (commercial AI stem separation).
    Moises,
    /// LANDR Stems (commercial).
    Landr,
    /// audioshake.ai (commercial).
    Audioshake,
    /// Native Instruments `.stem.mp4` format (multi-track container).
    NiStems,
    /// Hand-exported from a DAW.
    ManualExport,
    /// Unknown / unspecified.
    Unknown,
    /// Catch-all for sources not in this enum (e.g., a new tool not yet
    /// known to MeedyaSuite-core).
    Other(String),
}

// ============================================================
// Public API
// ============================================================

/// Read stem metadata from `tag`, if present.
///
/// Returns `None` only when no `StemRole` atom is set (since role is the
/// minimum required field for a stem). Other fields are filled if their
/// atoms are present; missing atoms become `None`.
pub fn read_stems(tag: &Tag) -> Option<StemMetadata> {
    let role = read_meedya_atom(tag, ATOM_ROLE).and_then(|s| StemRole::from_str(s).ok())?;
    Some(StemMetadata {
        role,
        instruments: read_meedya_atom(tag, ATOM_INSTRUMENTS)
            .map(|s| {
                s.split(',')
                    .map(str::trim)
                    .filter(|t| !t.is_empty())
                    .map(str::to_owned)
                    .collect()
            })
            .unwrap_or_default(),
        collection_id: read_meedya_atom(tag, ATOM_COLLECTION_ID).map(str::to_owned),
        parent_track_id: read_meedya_atom(tag, ATOM_PARENT_TRACK_ID).map(str::to_owned),
        source: read_meedya_atom(tag, ATOM_SOURCE)
            .and_then(|s| StemSource::from_str(s).ok())
            .unwrap_or(StemSource::Unknown),
        total_count: read_meedya_atom(tag, ATOM_TOTAL_COUNT).and_then(|s| s.parse().ok()),
        index: read_meedya_atom(tag, ATOM_INDEX).and_then(|s| s.parse().ok()),
        model_version: read_meedya_atom(tag, ATOM_MODEL_VERSION).map(str::to_owned),
    })
}

/// Write stem metadata to `tag`. Replaces any existing stem atoms.
pub fn write_stems(tag: &mut Tag, stems: &StemMetadata) {
    write_meedya_atom(tag, ATOM_ROLE, &stems.role.to_string());
    if !stems.instruments.is_empty() {
        write_meedya_atom(tag, ATOM_INSTRUMENTS, &stems.instruments.join(","));
    } else {
        clear_meedya_atom(tag, ATOM_INSTRUMENTS);
    }
    if let Some(id) = &stems.collection_id {
        write_meedya_atom(tag, ATOM_COLLECTION_ID, id);
    } else {
        clear_meedya_atom(tag, ATOM_COLLECTION_ID);
    }
    if let Some(pid) = &stems.parent_track_id {
        write_meedya_atom(tag, ATOM_PARENT_TRACK_ID, pid);
    } else {
        clear_meedya_atom(tag, ATOM_PARENT_TRACK_ID);
    }
    if !matches!(stems.source, StemSource::Unknown) {
        write_meedya_atom(tag, ATOM_SOURCE, &stems.source.to_string());
    } else {
        clear_meedya_atom(tag, ATOM_SOURCE);
    }
    if let Some(n) = stems.total_count {
        write_meedya_atom(tag, ATOM_TOTAL_COUNT, &n.to_string());
    } else {
        clear_meedya_atom(tag, ATOM_TOTAL_COUNT);
    }
    if let Some(n) = stems.index {
        write_meedya_atom(tag, ATOM_INDEX, &n.to_string());
    } else {
        clear_meedya_atom(tag, ATOM_INDEX);
    }
    if let Some(v) = &stems.model_version {
        write_meedya_atom(tag, ATOM_MODEL_VERSION, v);
    } else {
        clear_meedya_atom(tag, ATOM_MODEL_VERSION);
    }
}

/// Remove all stem atoms from `tag`.
pub fn clear_stems(tag: &mut Tag) {
    for name in [
        ATOM_ROLE,
        ATOM_INSTRUMENTS,
        ATOM_COLLECTION_ID,
        ATOM_PARENT_TRACK_ID,
        ATOM_SOURCE,
        ATOM_TOTAL_COUNT,
        ATOM_INDEX,
        ATOM_MODEL_VERSION,
    ] {
        clear_meedya_atom(tag, name);
    }
}

// ============================================================
// StemRole ↔ string
// ============================================================

impl fmt::Display for StemRole {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            StemRole::Drums => f.write_str("drums"),
            StemRole::Bass => f.write_str("bass"),
            StemRole::Vocals => f.write_str("vocals"),
            StemRole::Melody => f.write_str("melody"),
            StemRole::Harmony => f.write_str("harmony"),
            StemRole::Fx => f.write_str("fx"),
            StemRole::FullMix => f.write_str("full-mix"),
            StemRole::Other(s) => f.write_str(s),
        }
    }
}

impl FromStr for StemRole {
    type Err = ();
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let lower = s.to_ascii_lowercase();
        Ok(match lower.as_str() {
            "drums" | "drum" => StemRole::Drums,
            "bass" => StemRole::Bass,
            "vocals" | "vocal" => StemRole::Vocals,
            "melody" => StemRole::Melody,
            "harmony" => StemRole::Harmony,
            "fx" | "effects" => StemRole::Fx,
            "full-mix" | "full_mix" | "fullmix" => StemRole::FullMix,
            other if !other.is_empty() => StemRole::Other(other.to_owned()),
            _ => return Err(()),
        })
    }
}

// ============================================================
// StemSource ↔ string
// ============================================================

impl fmt::Display for StemSource {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            StemSource::Demucs => f.write_str("demucs"),
            StemSource::Spleeter => f.write_str("spleeter"),
            StemSource::Moises => f.write_str("moises"),
            StemSource::Landr => f.write_str("landr"),
            StemSource::Audioshake => f.write_str("audioshake"),
            StemSource::NiStems => f.write_str("ni-stems"),
            StemSource::ManualExport => f.write_str("manual-export"),
            StemSource::Unknown => f.write_str("unknown"),
            StemSource::Other(s) => f.write_str(s),
        }
    }
}

impl FromStr for StemSource {
    type Err = ();
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let lower = s.to_ascii_lowercase();
        Ok(match lower.as_str() {
            "demucs" => StemSource::Demucs,
            "spleeter" => StemSource::Spleeter,
            "moises" => StemSource::Moises,
            "landr" => StemSource::Landr,
            "audioshake" => StemSource::Audioshake,
            "ni-stems" | "ni_stems" | "nistems" => StemSource::NiStems,
            "manual-export" | "manual_export" | "manual" => StemSource::ManualExport,
            "unknown" | "" => StemSource::Unknown,
            other => StemSource::Other(other.to_owned()),
        })
    }
}

// ============================================================
// Tests
// ============================================================

#[cfg(test)]
mod tests {
    use super::*;
    use lofty::tag::TagType;

    fn fresh() -> Tag {
        Tag::new(TagType::Id3v2)
    }

    // ---- StemRole round-trip ----

    #[test]
    fn role_round_trip_canonical_variants() {
        for role in [
            StemRole::Drums,
            StemRole::Bass,
            StemRole::Vocals,
            StemRole::Melody,
            StemRole::Harmony,
            StemRole::Fx,
            StemRole::FullMix,
        ] {
            let s = role.to_string();
            let parsed: StemRole = s.parse().unwrap();
            assert_eq!(parsed, role);
        }
    }

    #[test]
    fn role_other_preserved() {
        let role = StemRole::Other("piano-only".to_owned());
        let parsed: StemRole = role.to_string().parse().unwrap();
        assert_eq!(parsed, role);
    }

    #[test]
    fn role_parses_singular_drum() {
        assert_eq!("drum".parse::<StemRole>().unwrap(), StemRole::Drums);
    }

    #[test]
    fn role_parses_underscore_variants() {
        assert_eq!("full_mix".parse::<StemRole>().unwrap(), StemRole::FullMix);
        assert_eq!("FULLMIX".parse::<StemRole>().unwrap(), StemRole::FullMix);
    }

    // ---- StemSource round-trip ----

    #[test]
    fn source_round_trip_canonical() {
        for src in [
            StemSource::Demucs,
            StemSource::Spleeter,
            StemSource::Moises,
            StemSource::Landr,
            StemSource::Audioshake,
            StemSource::NiStems,
            StemSource::ManualExport,
        ] {
            let parsed: StemSource = src.to_string().parse().unwrap();
            assert_eq!(parsed, src);
        }
    }

    #[test]
    fn source_unknown_round_trip() {
        let parsed: StemSource = StemSource::Unknown.to_string().parse().unwrap();
        assert_eq!(parsed, StemSource::Unknown);
    }

    #[test]
    fn source_other_preserved() {
        let src = StemSource::Other("custom-tool-v1".to_owned());
        let parsed: StemSource = src.to_string().parse().unwrap();
        assert_eq!(parsed, src);
    }

    // ---- Read/write through Tag ----

    #[test]
    fn read_empty_tag_returns_none() {
        assert_eq!(read_stems(&fresh()), None);
    }

    #[test]
    fn write_then_read_full_metadata() {
        let mut tag = fresh();
        let stems = StemMetadata {
            role: StemRole::Drums,
            instruments: vec![
                "kick".to_owned(),
                "snare".to_owned(),
                "hat".to_owned(),
                "tom".to_owned(),
            ],
            collection_id: Some("abc-123-uuid".to_owned()),
            parent_track_id: Some("musicbrainz:f0123".to_owned()),
            source: StemSource::Demucs,
            total_count: Some(4),
            index: Some(1),
            model_version: Some("demucs-v4.0.0-htdemucs".to_owned()),
        };
        write_stems(&mut tag, &stems);
        assert_eq!(read_stems(&tag), Some(stems));
    }

    #[test]
    fn write_minimal_role_only() {
        let mut tag = fresh();
        let stems = StemMetadata {
            role: StemRole::Vocals,
            instruments: vec![],
            collection_id: None,
            parent_track_id: None,
            source: StemSource::Unknown,
            total_count: None,
            index: None,
            model_version: None,
        };
        write_stems(&mut tag, &stems);
        assert_eq!(read_stems(&tag), Some(stems));
    }

    #[test]
    fn instruments_comma_separated_round_trip() {
        let mut tag = fresh();
        let stems = StemMetadata {
            role: StemRole::Drums,
            instruments: vec!["kick".into(), "snare".into()],
            collection_id: None,
            parent_track_id: None,
            source: StemSource::Unknown,
            total_count: None,
            index: None,
            model_version: None,
        };
        write_stems(&mut tag, &stems);
        // Raw atom check: comma-separated.
        assert_eq!(read_meedya_atom(&tag, ATOM_INSTRUMENTS), Some("kick,snare"));
    }

    #[test]
    fn instruments_tolerates_whitespace_on_read() {
        let mut tag = fresh();
        write_meedya_atom(&mut tag, ATOM_ROLE, "drums");
        write_meedya_atom(&mut tag, ATOM_INSTRUMENTS, "  kick ,  snare , hat ");
        let read = read_stems(&tag).unwrap();
        assert_eq!(read.instruments, vec!["kick", "snare", "hat"]);
    }

    #[test]
    fn instruments_drops_empty_segments() {
        let mut tag = fresh();
        write_meedya_atom(&mut tag, ATOM_ROLE, "drums");
        write_meedya_atom(&mut tag, ATOM_INSTRUMENTS, "kick,,snare,");
        let read = read_stems(&tag).unwrap();
        assert_eq!(read.instruments, vec!["kick", "snare"]);
    }

    #[test]
    fn source_unknown_written_as_absent() {
        // When `source` is Unknown, no atom should be written (avoids
        // emitting noise; absent reads back as Unknown anyway).
        let mut tag = fresh();
        let stems = StemMetadata {
            role: StemRole::Bass,
            instruments: vec![],
            collection_id: None,
            parent_track_id: None,
            source: StemSource::Unknown,
            total_count: None,
            index: None,
            model_version: None,
        };
        write_stems(&mut tag, &stems);
        assert_eq!(read_meedya_atom(&tag, ATOM_SOURCE), None);
    }

    #[test]
    fn clear_stems_removes_all_atoms() {
        let mut tag = fresh();
        write_stems(
            &mut tag,
            &StemMetadata {
                role: StemRole::Vocals,
                instruments: vec!["lead".into()],
                collection_id: Some("uuid".into()),
                parent_track_id: Some("pid".into()),
                source: StemSource::Moises,
                total_count: Some(4),
                index: Some(3),
                model_version: Some("v2".into()),
            },
        );
        clear_stems(&mut tag);
        assert_eq!(read_stems(&tag), None);
        // Spot-check a couple of side fields.
        assert_eq!(read_meedya_atom(&tag, ATOM_INSTRUMENTS), None);
        assert_eq!(read_meedya_atom(&tag, ATOM_SOURCE), None);
    }

    #[test]
    fn unknown_total_count_string_falls_back_to_none() {
        let mut tag = fresh();
        write_meedya_atom(&mut tag, ATOM_ROLE, "drums");
        write_meedya_atom(&mut tag, ATOM_TOTAL_COUNT, "not-a-number");
        let read = read_stems(&tag).unwrap();
        assert_eq!(read.total_count, None);
    }
}
